google_sheet_id = "1xGeEqZ0Y-o7XEIR0mOBvgvTk7FVRzz7TTGRKrSCy6Uo"
admin_password = "almakaki"

[gcp_service_account]
type = "service_account"
project_id = "mystic-fountain-300911"
private_key_id = "99c06264918cb61f3be5cae040fbf961c316a1c7"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCMPSRYOnVVreH+
wjvsvt+b9N0i4B1Jr9dmei7a6Y3mrmbw6N6g1wDFD8lIasOf9LApyelnqLJFNbbI
ea0WfADp9FyX11ugfNXZo+eBOOXXzttPnI3rwo82ECEvnQmdCzlikKi3wb1CI0oc
/2QZ6rxZbR0R2MaRc5yZC8B3nKgWpc4RYo9UYmGGONaFBbLHT8Titvj0iG3rDzD+
S5UDPP/7DpeSMBq1+WtZ0IMtHxNd/XX5rUVZ53EOX6uIp+6o5A4TvegLZuKhvKdf
qVolvYMZcLGObGW55k+2BqGxJzAiARFoFfZ2QwDY57hP7OGl25fyqbxNA4JdV4Z9
az/z7UoVAgMBAAECggEAAXKWH/UGhgpj9VHC9Zgozb7S04vVsY+HnS6wsiDMDrAJ
Lv5wYd+mSeJ2VPGJMGsBsIS9jIzgvjcmOl6LK1q/Varok8as0vTG7lazSpGwSbCA
cgtvKZpaCRhUh13LHhxiDMLqgu8UiYy8tJzsRxo1tIScUrVWo2S6npfQ9ksfLxCm
LKqWGV7QrazM7Humnl3KIbL0+O59fEsA34IEds6ilHiXPPDy+h2Oz1LhodYp/SK4
l4x/OkFc36RHHvTteZbug2QXtGhau1mj2izLfSBn3aVeTxWiSeaNqYAeNe4GpcJY
uSJRW+7zaDFqKJO66jLmvi4brUXv+5Ygzzu5EHgvcQKBgQDCXXXsG1EkgMAyyO/a
q4kwe/l0dTUpyzALAJT10FQlBPBzv+wCwYE8L7b0+MeWJHlI/xkZvL/AfZ9m5EGt
5J8RAfcxCdGSrZ6aeCe957FmdibEboOn4KBhzFpKYhrrD+XPviYrijAWVmPrNNab
6N4A4L4ZrvhTGAqkwAyaQ4NIjQKBgQC4tbe/bnTu4bf8vrS9zUnkQHyNz5BpexMe
Oq4eOX6P/pFKB41ZNSpykVXuDRA5L2ine/bVPTEZ9AdPt329o2HmDZLV2OGCxf+z
SgdRuUMss3jeAXfU607MZwNMIJolvkn/cqwO8UEku1hW2mtravGAtmZMASVjS1Aj
Qi6qKEc5qQKBgQCCaLrqRBnZaBmM+Y0VJurRgR0KqmmVNSNy/lzz4WfTvtCmmSr9
XmAbxdf33cPsVWSbOa3Zuu7ddGwzWQtIZZDklHEKkg/vXlaARgZEQOSiXrv8KDpl
tS1m8PnT1qdA+FW1YVuy8vD4y9YWxkkIKuJprGFgUimDdyoNCF5sUsgPMQKBgQCJ
pen7/82mY5GgCWJZ+41wStpHOAJPiQdTRLmTDpeRqU0OlRgx/ZvXaxVVZGjNpNXh
0lC80nAv/hogvwY2d3YyYbUmJgzQTstiCe3wahZ0Tn7pOsDZbE35p17esYEOVYOB
mSw9qm44eGC5wOXCVB0LJWKQi14YY/yheeWaqo+BmQKBgCaYp1a7s1mob+XNmiSc
VC8ZZypJzeSyMswTPMOCStQpqTaosQiYRxV8dBwwmNE7ZE2NnfyPdG8xBUJqRhTR
nW10LyjWSoxm/+lNGC1A4dtMcdu/BDWHUM3TNRLlza3xHCRyjMqDtP9W8E3Mj4Sd
NNyZqmEoSlRKm6gSpvU0F4Mg
-----END PRIVATE KEY-----"""
client_email = "streamlit-booking@mystic-fountain-300911.iam.gserviceaccount.com"
client_id = "109461143354701029434"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-booking%40mystic-fountain-300911.iam.gserviceaccount.com"
